require('dotenv').config();

const {
  NODE_ENV,
  PORT,
  DEVELOPMENT_MONGODB_URI,
  TEST_MONGODB_URI,
  PRODUCTION_MONGODB_URI,
  SECRET,
  DEVELOPMENT_ORIGIN,
  PRODUCTION_ORIGIN,
  DOMAIN,
} = process.env;

let MONGODB_URI = '';
let SECURE_COOKIE_CONFIG = null;
let SAME_SITE = null;
let ORIGIN = null;
if (NODE_ENV === 'development') {
  MONGODB_URI = DEVELOPMENT_MONGODB_URI;
  SECURE_COOKIE_CONFIG = false;
  SAME_SITE = false;
  ORIGIN = DEVELOPMENT_ORIGIN;
} else if (NODE_ENV === 'test') {
  MONGODB_URI = TEST_MONGODB_URI;
  SECURE_COOKIE_CONFIG = false;
  SAME_SITE = false;
  ORIGIN = DEVELOPMENT_ORIGIN;
} else if (NODE_ENV === 'production') {
  MONGODB_URI = PRODUCTION_MONGODB_URI;
  SECURE_COOKIE_CONFIG = true;
  SAME_SITE = 'none';
  ORIGIN = PRODUCTION_ORIGIN;
}

module.exports = {
  MONGODB_URI,
  PORT,
  SECRET,
  SECURE_COOKIE_CONFIG,
  SAME_SITE,
  ORIGIN,
  DOMAIN,
};
